require: 
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Include:
    - 'app/controllers/api/v1/**/*'
    - 'app/models/**/*'
    - 'db/**/*'
    - 'config/routes.rb'
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 1
  Width: 1
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line
Rails/DynamicFindBy:
  Enabled: false